### ISSUE TITLE
Graphical Corruption

### ISSUE THREAD

**Issue by shadowartist201** [shadowartist201/TKA-PC-Port#1]
For an unknown reason, many of the .xnb graphics seem to have color and transparency corruption. Pulling a fresh copy of the files does nothing. 

May need to pull alternate images from the mobile versions of TKA.

![splash_bgMenu](https://user-images.githubusercontent.com/85422109/189187263-e2b061bf-88f9-4750-a9fc-6eae89a005c0.png)

![SplashMenu](https://user-images.githubusercontent.com/85422109/189187330-4c5b2aee-1a18-482a-bb78-0618def9bbc9.png)

**Comment by shadowartist201** [comment]
Unsure if the corruption is caused by my XNB to PNG tools, or whether everything is like that. Monogame's content pipeline is loading them incorrectly too.

**Comment by shadowartist201** [comment]
[XNB_Format.docx](https://github.com/shadowarti
[test files.zip](https://github.com/shadowartist201/TKA-PC-Port/files/9896100/test.files.zip)
st201/TKA-PC-Port/files/9896098/XNB_Format.docx)

**Comment by shadowartist201** [comment]
Investigated further. Raw image data (RGBA) is different while the headers are fine. Maybe this is a problem with the dumping process from 360? Other XNA games dumped have this issue.

**Comment by BarkovMA** [comment]
> Investigated further. Raw image data (RGBA) is different while the headers are fine. Maybe this is a problem with the dumping process from 360? Other XNA games dumped have this issue.

Hey! I had some familiar problem with graphics while trying to export textures from Unity game with AssetStudio. It figured out that program recognized wrong colour format (ARGB instead of RGBA). In other words, colours and alpha channels was mixed up. Textures in your port really looks like it have the same problem. Try to rearrange colours and alpha channels in code, if you know how, or to change colour format recognition which the game is using.

**Comment by shadowartist201** [comment]
> In other words, colours and alpha channels was mixed up.

I figured it was some kind of color channel mixup but even when moving things to the correct location, there's still something off. I'm not sure why Red is the only layer that is correct. Maybe it's data transfer corruption from the 360?

### RGBA layers of .XNB image
![189187263-e2b061bf-88f9-4750-a9fc-6eae89a005c0-RGBA](https://user-images.githubusercontent.com/85422109/213776834-f83a0376-1fe7-42bd-9da0-2c106f3f5741.png)

### Ideal RGBA layers
![189187330-4c5b2aee-1a18-482a-bb78-0618def9bbc9-RGBA](https://user-images.githubusercontent.com/85422109/213776397-21afb0eb-23b1-4f4c-8328-a9a710e2f843.png)

**Comment by shadowartist201** [comment]
Pulled the images with a better decompiler and swapped the ARGB with RGBA. Came out mostly well aside from some Alpha layers showing up as Cyan (I believe they're supposed to be shaders instead?)

![dream](https://user-images.githubusercontent.com/85422109/213841288-4be0e0b4-ec30-4453-9bd3-8be3f5f8277b.png)
![menu'](https://user-images.githubusercontent.com/85422109/213841289-a2eafd86-3739-4870-addb-a4042d2c3723.png)
![stats](https://user-images.githubusercontent.com/85422109/213841290-facbb5bc-b31e-4bed-8235-b1f3c79cd767.png)
![credits'](https://user-images.githubusercontent.com/85422109/213841291-0c70287c-34d1-45fd-b9af-074d1246d37c.png)
![options](https://user-images.githubusercontent.com/85422109/213841292-df13cb6f-46cb-43e9-a535-c79a753f2034.png)
![meat](https://user-images.githubusercontent.com/85422109/213841293-855dcf3f-4e8b-4d69-a17e-fc54bfe0f1bc.png)
![lava](https://user-images.githubusercontent.com/85422109/213841294-df5f4a61-dabb-4ab9-8540-6cc4fdec486d.png)
![cloud](https://user-images.githubusercontent.com/85422109/213841296-39b57059-856c-447a-8db6-37a256f39516.png)
![title](https://user-images.githubusercontent.com/85422109/213841297-c2f9cd44-5786-4b78-ad5c-f6e750a67329.png)
![pause](https://user-images.githubusercontent.com/85422109/213841298-fc4f2704-b8b7-4288-a7b2-e5cb7fa99bad.png)
![popaganda](https://user-images.githubusercontent.com/85422109/213841299-f76e5d91-9e35-42ad-bfcd-040025e94383.png)

**Comment by shadowartist201** [comment]
Re-unpacked XNBs using https://github.com/antag99/TExtract and finally the channels are intact. All images showing normal.

![image](https://user-images.githubusercontent.com/85422109/213846139-d680d0c2-bcbf-44fa-ba2b-8b3d1bc7030a.png)
