### ISSUE TITLE
Permanent rainbow bug after playing Nyan Pack

### ISSUE THREAD

**Issue by mredgyskele** [shadowartist201/TKA-PC-Port#11]
Was messing around with the new 0.2 beta, playing the Nyan Pack, of course had the rainbow effect. Only after switching levels, the rainbow effect is permanently on screen for other levels until a restart. 
![rainboweffectbug](https://github.com/shadowartist201/TKA-PC-Port/assets/143831085/5a1387ce-f41f-4b48-8111-bddb54687223)

**Comment by shadowartist201** [comment]
I suspect this is an issue with the rainbow overlay not being reset in `Game1.ResetChoreography()`.

**Comment by shadowartist201** [comment]
Fixed in d04b8e11
