### ISSUE TITLE
[All] Animated bg sprites for Nyan Pack are not coded properly

### ISSUE THREAD

**Issue by FileKarl** [shadowartist201/TKA-PC-Port#12]
![image](https://github.com/shadowartist201/TKA-PC-Port/assets/109991414/3061ff99-9cf5-41eb-9198-de7ab4b1c490)

**Comment by shadowartist201** [comment]
Known issue. Due to incorrect bounds on bg sprites. Need to update bounds.

**Comment by shadowartist201** [comment]
Determined boundaries, fixed in ede5bbc

![nyanBackgroundSprites](https://github.com/shadowartist201/TKA-PC-Port/assets/85422109/4f0d884b-6e53-4599-91a7-2942a93d3344)
