### ISSUE TITLE
[All] Broken Camera - Popaganda

### ISSUE THREAD

**Issue by shadowartist201** [shadowartist201/TKA-PC-Port#3]
Camera effects are totally inoperable in Propaganda Pack. Per VS, "System.NullReferenceException: 'Object reference not set to an instance of an object.'"

All camera effects have therefore been commented out.

**Comment by shadowartist201** [comment]
Example line: `Camera.effects[Camera.effectIndex].Parameters["Offset"].SetValue(new Vector2((float)Math.Cos(Camera.theta), (float)Math.Sin(Camera.theta)));`

In which `Camera.effects[]` is an array of size 5 and all null at this point. `Camera.effectIndex` starts at 0.

In theory, it should be setting the value of either `Camera.effects[0].Parameters["Offset"]` or `Camera.effects[0]`. I can initialize `Camera.effects[]` with a simple effect, but that doesn't make `Offset` appear.

**Comment by shadowartist201** [comment]
Maybe it's possible to initialize `Camera.effects[]` using the effect files within `Content/Effects/`. I'm assuming it's supposed to be done like that since the files aren't used anywhere else. I'm not good enough at XNA to load them in though. And there's an 80% chance the effects are corrupted too and I'm unable to restore them.

**Comment by weegeeday** [comment]
I tried passing the effects in that folder in mgfxc, witch is used to convert the effects. it could not do it. I think the effect files are actually corrupted. I have no other point as reference as they are not inside the windows phone app, it seems that the xnb formats are also different. (eg in a hex editor xbox 360 xnb's start with XNBx, windows phone with XNBm.) Not too sure whats going on, and they seem to be used.

**Comment by shadowartist201** [comment]
Upon opening the XNBs in `Content/Effects/`, they seem to be .CSO files (compiles shader objects, a compiled .HLSL file from Visual Studio). I have no way of decompiling them at this time to be compatible with Monogame.

**Comment by shadowartist201** [comment]
It seems the only solution is to rewrite the HLSL. The compiled code we have is assembly, and even if I could piece it back together, it would lack things such as variable names and HLSL's normal structure.

**Comment by weegeeday** [comment]
How many HLSL files would need to be rewritten?

**Comment by shadowartist201** [comment]
There are five original files, with some containing multiple effects.

**Comment by weegeeday** [comment]
alright, good to know. il see if i can learn to write HLSL files, doesnt seem too bad.

**Comment by weegeeday** [comment]
is there a tool to open the original effect xnbs or no?

**Comment by weegeeday** [comment]
apparently visual studio 2015's Shader Designer can load CSO files. if it works, this should make it easier to recreate in HLSL format or something.

**Comment by weegeeday** [comment]
it cant, only exports them. and the shader designer is available on the newer versions too.

**Comment by weegeeday** [comment]
do we know what effect file is for which level?

**Comment by shadowartist201** [comment]
The effect files correspond to different effects, not necessarily to different levels. Popaganda Pack seems to use them as listed below:

- effect0 -- left/right shaking, seen at the beginning of the stage
- effect1 -- dark filter with outline
- effect2 -- grid of circles with negative filter
- effect3 -- sin wave filter, reminds me of water
- effect4 -- aggresive shaking, seen at the end of the stage

I would recommend using a YouTube video of the level as a reference. I also found some good references on Shadertoy.

**Comment by shadowartist201** [comment]
Effects 1, 2, and 3 have been created and added in cdd8ffe
![circles](https://github.com/shadowartist201/TKA-PC-Port/assets/85422109/7edb19ca-8f21-4370-8313-d33c95425a64)
![wave](https://github.com/shadowartist201/TKA-PC-Port/assets/85422109/f7bba5d1-3664-4b96-855f-2c53ff1f0228)
![attempt 3 5](https://github.com/shadowartist201/TKA-PC-Port/assets/85422109/72777828-c51a-43c0-826e-3731d6537e6e)

**Comment by shadowartist201** [comment]
Beta shaders that have been sitting in my notes for ages:
- rotate this [top/bottom shaking](https://www.shadertoy.com/view/ctVBRh) for effect0 (left/right shaking)
- intensify this [shaking](https://www.shadertoy.com/view/DtVBRh) and add a blur effect for effect4 (aggressive shaking)

**Comment by shadowartist201** [comment]
Effect 0 has been added, but not for the later appearance of super aggressive shaking. Might write a separate shader for that.
Also Effect 4 is C-path movement and not done yet.
![image](https://github.com/shadowartist201/TKA-PC-Port/assets/85422109/a8705a8d-12e5-4eb9-a560-8d1743292c7e)

**Comment by shadowartist201** [comment]
Added Effect 4. It doesn't swing as much as I'd like it to, but it gets really messy when you try to change it. Thanks for Gemini Advanced's help to write this and Effect 0.

**Comment by shadowartist201** [comment]
Added Effect 5 in 63a01a4 (the drunk effect that wildly swings).
