### ISSUE TITLE
cant even get it to to load

### ISSUE THREAD

**Issue by mewmon0w0** [shadowartist201/TKA-PC-Port#5]
I am confused af it just says it doesnt exist I read the read me and did what I was suposed to really confused

**Comment by shadowartist201** [comment]
The readme is not an instruction manual. Please ensure you have the correct version of .NET installed and check your nuget packages for Monogame. You will also need the C# debugger to build the game.

**Comment by mewmon0w0** [comment]
how do I install .net

**Comment by mewmon0w0** [comment]
cant find C# debugger

**Comment by mewmon0w0** [comment]
oh I already had .net

**Comment by mewmon0w0** [comment]
I think its fucked

**Comment by mewmon0w0** [comment]
can you PLEASE upload a video tutorial

**Comment by shadowartist201** [comment]
Post your build errors.

**Comment by mewmon0w0** [comment]
Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB3644	The reference assemblies for framework ".NETFramework,Version=v0.0" were not found. To resolve this, install the SDK or Targeting Pack for this framework version or retarget your application to a version of the framework for which you have the SDK or Targeting Pack installed. Note that assemblies will be resolved from the Global Assembly Cache (GAC) and will be used in place of reference assemblies. Therefore your assembly may not be correctly targeted for the framework you intend.	test	C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets	1179

**Comment by mewmon0w0** [comment]
the debug executable 'D:downloads/TKA-PC-Port-WGD-main/test/bin/Debug/Test.exe' specified in the 'test' debug profile does not exist.

**Comment by mewmon0w0** [comment]
1>------ Build started: Project: test, Configuration: Debug Any CPU ------
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Sdks\Microsoft.NET.Sdk\build\Microsoft.NET.TargetFrameworkInference.targets(84,5): error : Cannot infer TargetFrameworkIdentifier and/or TargetFrameworkVersion from TargetFramework='net6.0-windows'. They must be specified explicitly.
1>Done building project "test.csproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

**Comment by mewmon0w0** [comment]
those are all my errors

**Comment by shadowartist201** [comment]
You need .NET Framework 6.0. It appears that Visual Studio 2017 doesn't support .NET 6.0 development, so I would suggest upgrading to the newest version of Visual Studio and trying again.
