### ISSUE TITLE
[FNA] Possible different method to port to PC

### ISSUE THREAD

**Issue by weegeeday** [shadowartist201/TKA-PC-Port#8]
i found that theres an open-source way to port XNA games, FNA seems to be a drag and drop solution, and could support the effects and such maybe.
[FNA Github](https://github.com/FNA-XNA/FNA)

**Comment by shadowartist201** [comment]
I have played around with FNA and it's still unable to load the effects. I intend to make a new commit with FNA eventually since it supports the Meat Pack Visualizer natively.

**Comment by shadowartist201** [comment]
This is now a new branch specifically for Windows
